#! /bin/bash
ecasound -x -z:nodb -b:1024 -z:mixmode,sum \
-a:pre -pf:/etc/ampCtl/pre.ecp -i:alsa,hw:0,0 -o:loop,1 \
-a:woofer,tweeter -i:loop,1 \
-a:woofer -pf:/etc/ampCtl/woofer.ecp -f:16,2,44100 -o:alsa,sysdefault:CARD=Audio \
-a:tweeter -pf:/etc/ampCtl/tweeter.ecp -f:16,2,44100 -o:alsa,sysdefault:CARD=Audio_1

